# Generated by Django 4.2.5 on 2023-09-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_receipt_type', models.CharField(choices=[('Pickup', 'Самовывоз'), ('Delivery', 'Доставка')], default='Delivery', max_length=100, verbose_name='Вид получения товара')),
                ('total_price', models.PositiveIntegerField(verbose_name='Итоговая цена товаров')),
                ('payment_code', models.CharField(max_length=20, unique=True, verbose_name='Код оплаты биллинга')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания биллинга')),
            ],
            options={
                'verbose_name': 'Биллинг',
                'verbose_name_plural': 'Биллинги',
            },
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товаров')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_products', to='billing.billing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
