# Generated by Django 4.2.5 on 2023-09-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_billingproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproduct',
            name='price',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Цена товара'),
            preserve_default=False,
        ),
    ]
