# Generated by Django 4.2.5 on 2023-09-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
