# Generated by Django 4.2.5 on 2023-09-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproduct',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Цена товара'),
        ),
    ]
