# Generated by Django 4.2.5 on 2023-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_billingproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_receipt_type',
            field=models.CharField(choices=[('Pickup', 'Самовывоз'), ('Delivery', 'Доставка')], default='Самовывоз', max_length=100, verbose_name='Вид получения товара'),
        ),
    ]
