# Generated by Django 4.2.5 on 2023-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_billing_billing_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='phone',
            field=models.CharField(default=1, max_length=200, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
