# Generated by Django 4.2.5 on 2023-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billing_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproduct',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='billingproduct',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Итоговая цена'),
        ),
    ]
