# Generated by Django 4.2.5 on 2023-09-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billingproduct_status_alter_billingproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(default=1, max_length=100, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
