# Generated by Django 4.2.5 on 2023-09-28 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_billing_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
