# Generated by Django 4.2.5 on 2023-09-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_billingproduct_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Summary',
                'verbose_name_plural': 'Sales Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billing',),
        ),
    ]
