# Generated by Django 4.2.5 on 2023-09-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_salesummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesummary',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
    ]
