# Generated by Django 4.2.5 on 2023-09-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_salesummary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesummary',
            options={'verbose_name': 'Продажа товар', 'verbose_name_plural': 'Продажи товаров'},
        ),
    ]
