# Generated by Django 4.2.5 on 2023-09-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_salesummary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesummary',
            options={'verbose_name': 'Отчет продажа товар', 'verbose_name_plural': 'Отчеты продажи товаров'},
        ),
    ]
