# Generated by Django 4.2.5 on 2023-09-29 02:31

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_billingproduct_level_billingproduct_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproduct',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='billing.billingproduct'),
        ),
    ]
