# Generated by Django 4.2.5 on 2023-09-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_delete_salesummary_salesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleSummary',
        ),
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Отчет продажа товар',
                'verbose_name_plural': 'Отчеты продажи товаров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billing',),
        ),
    ]
