# Generated by Django 4.2.5 on 2023-09-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_delete_salesummary_salesummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingproduct',
            name='parent',
        ),
    ]
