# Generated by Django 4.2.5 on 2023-09-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_remove_billingproduct_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingproduct',
            name='level',
        ),
        migrations.RemoveField(
            model_name='billingproduct',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='billingproduct',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='billingproduct',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='billing',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
