# Generated by Django 4.2.5 on 2023-09-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_tolal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='tolal',
            new_name='total',
        ),
    ]
