# Generated by Django 4.2.5 on 2023-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_tolal_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Итоговая цена товаров'),
        ),
    ]
