# Generated by Django 4.2.6 on 2023-10-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code_image',
            field=models.ImageField(default=1, upload_to='qr_codes/', verbose_name='QR код'),
            preserve_default=False,
        ),
    ]
