# Generated by Django 4.2.6 on 2023-10-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер стола'),
        ),
    ]
