# Generated by Django 4.2.6 on 2023-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR код'),
        ),
    ]
