# Generated by Django 4.2.6 on 2023-10-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_table_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
