# Generated by Django 4.2.5 on 2023-09-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='user_role',
            field=models.CharField(choices=[('User', 'Пользователь'), ('Delivery', 'Курьер'), ('Manager', 'Менеджер')], default='Пользователь', max_length=100, verbose_name='Роль пользователя'),
        ),
    ]
