# Generated by Django 4.2.5 on 2023-09-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_billing_payment_method'),
        ('telegram', '0002_telegramuser_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('Accepted', 'Принят'), ('On way', 'В пути'), ('Delivered', 'Доставлен')], max_length=100, verbose_name='Статус доставки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billing', verbose_name='Биллинг')),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доставка товара',
                'verbose_name_plural': 'Доставка товаров',
            },
        ),
        migrations.CreateModel(
            name='BillingDeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to='telegram.billingdelivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'История доставки',
                'verbose_name_plural': 'История доставок',
            },
        ),
    ]
