# Generated by Django 4.2.5 on 2023-09-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_billingdelivery_billingdeliveryhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingdelivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
    ]
